apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      type: pipeline
      version: v1
  template:
    metadata:
      labels:
        type: pipeline
        version: v1
    spec:
      containers:
        - name: demoapp
          image: jinbaeco/demo_app:36
          ports:
            - containerPort: 8080  